config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'devise/sessions' }
  resources :projects
  resources :project_clients
  resources :companies
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
#   devise_for :users, skip: [:registrations]
#   as :user do
#   get 'login', to: 'devise/sessions#new', as: :new_user_session
#   post 'login', to: 'devise/sessions#create', as: :user_session
  # get 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
# end

  
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "user#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  after_create :create_tenant

  private
  def create_tenant
    Apartment::Tenant.create(subdomain)
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :project_client
end

app/models/project_client.rb
class ProjectClient < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :send_welcome_email

	private

	def send_welcome_email
		UserMailer.welcome_email(self).deliver_now
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def after_sign_in_path_for(resource)
    root_path
  end
    
  def after_sign_out_path_fo
     root_url("localhost:3000", allow_other_host: true)
  end
  
end

app/controllers/companies_controller.rb
class CompaniesController < InheritedResources::Base


  private

    def company_params
      params.require(:company).permit(:name, :subdomain, :user_id)
    end

end

app/controllers/project_clients_controller.rb
class ProjectClientsController < InheritedResources::Base

  private

    def project_client_params
      params.require(:project_client).permit(:name, :address, :contact_no, :contact_support)
    end

end

app/controllers/projects_controller.rb
class ProjectsController < InheritedResources::Base

  private

    def project_params
      params.require(:project).permit(:name, :description, :project_client_id)
    end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
    def index 
        @users = User.all 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/project_clients_helper.rb
module ProjectClientsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/companies/_company.html.erb
<div id="<%= dom_id company %>">
  <p>
    <strong>Name:</strong>
    <%= company.name %>
  </p>

  <p>
    <strong>Subdomain:</strong>
    <%= company.subdomain %>
  </p>

  <p>
    <strong>User:</strong>
    <%= company.user_id %>
  </p>

</div>

app/views/companies/_form.html.erb
<%= form_with(model: company) do |form| %>
  <% if company.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :subdomain, style: "display: block" %>
    <%= form.text_field :subdomain %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render "form", company: @company %>

<br>

<div>
  <%= link_to "Show this company", @company %> |
  <%= link_to "Back to companies", companies_path %>
</div>

app/views/companies/index.html.erb
<h1>Companies</h1>

<div id="companies">
  <% @companies.each do |company| %>
    <%= render company %>
    <p>
      <%= link_to "Show this company", company %>
      <%= link_to "Sub Domain", "http://#{company.subdomain}.lvh.me:3000/project_clients" %>
      </p>
  <% end %>
</div>

<%= link_to "New company", new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render "form", company: @company %>

<br>

<div>
  <%= link_to "Back to companies", companies_path %>
</div>

app/views/companies/show.html.erb
<% if user_signed_in? %>
  <p style="color: green"><%= notice %></p>

  <%= render @company %>

  <div>
    <%= link_to "Show this company", company_path(@company) %> |
    <%= link_to "Edit this company", edit_company_path(@company) %> |
    <%= link_to "Back to companies", companies_path %>

    <%= button_to "Destroy this company", @company, method: :delete %>
  </div>
<% else %>
  <p>Please login to view this content.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Company_Management</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" 
     integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/project_clients/_form.html.erb
<%= form_with(model: project_client) do |form| %>
  <% if project_client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project_client.errors.count, "error") %> prohibited this project_client from being saved:</h2>

      <ul>
        <% project_client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :contact_no, style: "display: block" %>
    <%= form.number_field :contact_no %>
  </div>

  <div>
    <%= form.label :contact_support, style: "display: block" %>
    <%= form.text_field :contact_support %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/project_clients/_project_client.html.erb
<div id="<%= dom_id project_client %>">
  <p>
    <strong>Name:</strong>
    <%= project_client.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= project_client.address %>
  </p>

  <p>
    <strong>Contact no:</strong>
    <%= project_client.contact_no %>
  </p>

  <p>
    <strong>Contact support:</strong>
    <%= project_client.contact_support %>
  </p>

</div>

app/views/project_clients/edit.html.erb
<h1>Editing project client</h1>

<%= render "form", project_client: @project_client %>

<br>

<div>
  <%= link_to "Show this project client", @project_client %> |
  <%= link_to "Back to project clients", project_clients_path %>
</div>

app/views/project_clients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Project clients</h1>

<div id="project_clients">
  <% @project_clients.each do |project_client| %>
    <%= render project_client %>
    <p>
      <%= link_to "Show this project client", project_client %>
    </p>
  <% end %>
</div>

<%= link_to "New project client", new_project_client_path %>

app/views/project_clients/new.html.erb
<h1>New project client</h1>

<%= render "form", project_client: @project_client %>

<br>

<div>
  <%= link_to "Back to project clients", project_clients_path %>
</div>

app/views/project_clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project_client %>

<div>
  <%= link_to "Edit this project client", edit_project_client_path(@project_client) %> |
  <%= link_to "Back to project clients", project_clients_path %>

  <%= button_to "Destroy this project client", @project_client, method: :delete %>
</div>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :project_client_id, style: "display: block" %>
    <%= form.text_field :project_client_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>Project client:</strong>
    <%= project.project_client_id %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #0E7F6C ">
  <% if user_signed_in? || request.path == project_clients_path || request.path == projects_path %>
    <% if request.subdomain.present? %>
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to 'Project Client', project_clients_path, class: 'nav-link text-white',style: 'font-size: 20px;' %>
        </li>
      </ul>

      <% if ProjectClient.any? %>
        <ul class="navbar-nav">
          <%= link_to 'Projects', projects_path, class: 'nav-link text-white',style: 'font-size: 20px;' %>
        </ul>
      <% end %>
    <% else %>
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to 'Companies', companies_path, class: 'nav-link text-white',style: 'font-size: 20px;' %>
        </li>
      </ul>
    <% end %>

    <ul class="navbar-nav">
      <li class="nav-item active">
       
        <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: 'nav-link', data: { confirm: 'Are you sure?' } %>

      </li>
    </ul>
  <% else %>
    
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= button_to 'Login', new_user_session_path, class: 'nav-link' %>
        </li>
      </ul>
   
  <% end %>
</nav>